version: '3.1'

services:

  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'sistem_penilaian_mahasiswa'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  ports:
    - '8080:80'
  environment:
    PMA_HOST: db
    PMA_USER: root
    PMA_PASSWORD: root_password
  depends_on:
    - db

